# Generated by Django 5.1.7 on 2025-03-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0003_chatmessage_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='title',
            field=models.CharField(default='Yeni Chat', max_length=100),
        ),
    ]
