# Generated by Django 5.1.7 on 2025-03-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0004_chatmessage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='feedback',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10, null=True),
        ),
    ]
